spring:
  profiles:
    active: memory
  data:
    redis:
      repositories:
        enabled: false
logging:
  level:
    org.springframework: INFO

---

spring:
  profiles: redis
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6379
