server:
  port: 8080
  
spring:
  application:
     name: myApp
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /my-health-check
        healthCheckInterval: 20s
      